/* GENERATED by Engines/Marketing/tools/gen_intake_ts.py -- do not hand-edit.
 * Source: Engines/Marketing/reference/buyer_intake_schema.json
 * Form "buyer_intake" v1.0.0 -- 52 fields.
 * Regenerate after any schema change so the form, the validator, the printed
 * PDF and the Supabase table cannot drift apart.
 */
import { z } from 'zod';

export const buyerIntakeSchema = z.object({
  full_name: z.string().trim().max(300).min(1, 'Required'),
  cobuyer_name: z.literal('').or(z.string().trim().max(300)).optional(),
  email: z.string().trim().email('Enter a valid email').max(300).min(1, 'Required'),
  cobuyer_email: z.literal('').or(z.string().trim().email('Enter a valid email').max(300)).optional(),
  phone: z.string().trim().min(7, 'Enter a valid phone number').max(300).min(1, 'Required'),
  cobuyer_phone: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  current_address: z.literal('').or(z.string().trim().max(300)).optional(),
  cobuyer_relationship: z.literal('').or(z.string().trim().max(300)).optional(),
  preferred_contact: z.literal('').or(z.enum(["Text", "Call", "Email"])).optional(),
  best_contact_time: z.array(z.enum(["Morning", "Afternoon", "Evening"])).max(40).optional(),
  employment_status: z.literal('').or(z.enum(["Full-time", "Part-time", "Self-employed", "Retired", "Student", "Between jobs"])).optional(),
  years_employed: z.literal('').or(z.enum(["Under 1", "1 - 2", "2 - 5", "5+"])).optional(),
  financing_type: z.literal('').or(z.enum(["Conventional", "FHA", "VA", "USDA", "Cash", "Not sure yet"])).optional(),
  preapproval_status: z.literal('').or(z.enum(["Not started", "In progress", "Pre-approved"])).optional(),
  lender_name: z.literal('').or(z.string().trim().max(300)).optional(),
  preapproval_amount: z.coerce.number().nonnegative().optional(),
  max_purchase_price: z.coerce.number().nonnegative().optional(),
  comfortable_max_monthly_payment: z.coerce.number().nonnegative().optional(),
  down_payment_amount: z.coerce.number().nonnegative().optional(),
  down_payment_source: z.literal('').or(z.enum(["Savings", "Gift", "Sale of current home", "Retirement / 401k", "Other"])).optional(),
  credit_range: z.literal('').or(z.enum(["Below 580", "580–619", "620–679", "680–739", "740+", "Not sure"])).optional(),
  first_time_buyer: z.boolean().optional(),
  must_sell_first: z.boolean().optional(),
  target_move_date: z.literal('').or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD')).optional(),
  timeline_urgency: z.literal('').or(z.enum(["Immediately", "1–3 months", "3–6 months", "6–12 months", "Just starting to look"])).optional(),
  lease_end_date: z.literal('').or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD')).optional(),
  important_dates: z.literal('').or(z.string().trim().max(4000)).optional(),
  target_areas: z.literal('').or(z.string().trim().max(4000)).optional(),
  school_district: z.literal('').or(z.string().trim().max(300)).optional(),
  commute_to: z.literal('').or(z.string().trim().max(300)).optional(),
  max_commute_minutes: z.coerce.number().nonnegative().int().optional(),
  property_types: z.array(z.enum(["Single family", "Condo", "Townhouse", "Duplex", "Multi-family (3–4 unit)"])).max(40).optional(),
  beds_min: z.coerce.number().nonnegative().int().optional(),
  baths_min: z.coerce.number().nonnegative().optional(),
  sqft_min: z.coerce.number().nonnegative().int().optional(),
  garage_spaces_min: z.coerce.number().nonnegative().int().optional(),
  basement_preference: z.literal('').or(z.enum(["Must be finished", "Unfinished is fine", "No basement needed", "No preference"])).optional(),
  condition_tolerance: z.literal('').or(z.enum(["Move-in ready only", "Light cosmetic (paint, flooring)", "Moderate updating", "Full rehab / project"])).optional(),
  must_haves: z.literal('').or(z.string().trim().max(4000)).optional(),
  deal_breakers: z.literal('').or(z.string().trim().max(4000)).optional(),
  nice_to_haves: z.literal('').or(z.string().trim().max(4000)).optional(),
  household_size: z.coerce.number().nonnegative().int().optional(),
  pets: z.literal('').or(z.string().trim().max(300)).optional(),
  occupations: z.literal('').or(z.string().trim().max(300)).optional(),
  works_from_home: z.boolean().optional(),
  motivation: z.literal('').or(z.string().trim().max(4000)).optional(),
  past_experience: z.literal('').or(z.string().trim().max(4000)).optional(),
  what_matters_most: z.literal('').or(z.string().trim().max(4000)).optional(),
  referral_source: z.literal('').or(z.enum(["Referral from a friend or family member", "Past client", "Website", "Social media", "Open house", "Zillow / Realtor.com", "Other"])).optional(),
  referred_by: z.literal('').or(z.string().trim().max(300)).optional(),
  agency_ack: z.boolean().refine((v) => v === true, 'Required'),
  contact_consent: z.boolean().refine((v) => v === true, 'Required'),
});

export type BuyerIntakeValues = z.infer<typeof buyerIntakeSchema>;

export interface FieldMeta {
  id: string; label: string; kind: string;
  options?: string[]; required?: boolean; help?: string; sensitive?: boolean;
  columns?: { id: string; label: string }[];
}
export interface FieldGroup {
  id: string; title: string; help?: string; fields: FieldMeta[];
}

/* Rendering order and PDF walk order. Both modes iterate THIS, so the printed
 * packet and the web form cannot present different field sets. */
export const FIELD_GROUPS: FieldGroup[] = [
  {
    id: "contact", title: "Your contact information",
    fields: [
      { id: "full_name", label: "Full name", kind: "text", required: true },
      { id: "cobuyer_name", label: "Co-buyer name", kind: "text" },
      { id: "email", label: "Email", kind: "email", required: true },
      { id: "cobuyer_email", label: "Co-buyer email", kind: "email" },
      { id: "phone", label: "Cell phone", kind: "tel", required: true },
      { id: "cobuyer_phone", label: "Co-buyer phone", kind: "tel" },
      { id: "current_address", label: "Current address", kind: "text" },
      { id: "cobuyer_relationship", label: "Relationship to you", kind: "text" },
      { id: "preferred_contact", label: "Preferred contact method", kind: "select", options: ["Text", "Call", "Email"] },
      { id: "best_contact_time", label: "Best time to reach you", kind: "multiselect", options: ["Morning", "Afternoon", "Evening"] },
    ],
  },
  {
    id: "financing", title: "Financing",
    fields: [
      { id: "employment_status", label: "Current employment status", kind: "select", options: ["Full-time", "Part-time", "Self-employed", "Retired", "Student", "Between jobs"], help: "Self-employed changes the pre-approval conversation, so it is worth knowing early." },
      { id: "years_employed", label: "Years at current employer", kind: "select", options: ["Under 1", "1 - 2", "2 - 5", "5+"] },
      { id: "financing_type", label: "How are you financing?", kind: "select", options: ["Conventional", "FHA", "VA", "USDA", "Cash", "Not sure yet"] },
      { id: "preapproval_status", label: "Pre-approval status", kind: "select", options: ["Not started", "In progress", "Pre-approved"], help: "If you are not pre-approved yet that is fine — it is the first thing we will fix." },
      { id: "lender_name", label: "Lender (if you have one)", kind: "text" },
      { id: "preapproval_amount", label: "Pre-approval amount", kind: "money", sensitive: true },
      { id: "max_purchase_price", label: "Maximum purchase price you want to consider", kind: "money" },
      { id: "comfortable_max_monthly_payment", label: "Comfortable maximum monthly payment", kind: "money", help: "The number that actually governs the search — more useful than a purchase price. Include taxes and insurance." },
      { id: "down_payment_amount", label: "Down payment available", kind: "money", sensitive: true },
      { id: "down_payment_source", label: "Source of down payment", kind: "select", options: ["Savings", "Gift", "Sale of current home", "Retirement / 401k", "Other"], sensitive: true },
      { id: "credit_range", label: "Approximate credit score range", kind: "select", options: ["Below 580", "580–619", "620–679", "680–739", "740+", "Not sure"], sensitive: true },
      { id: "first_time_buyer", label: "Is this your first home purchase?", kind: "boolean" },
      { id: "must_sell_first", label: "Do you need to sell a home before buying?", kind: "boolean" },
    ],
  },
  {
    id: "timeline", title: "Timeline",
    fields: [
      { id: "target_move_date", label: "Ideal move-in date", kind: "date" },
      { id: "timeline_urgency", label: "How soon are you looking to buy?", kind: "select", options: ["Immediately", "1–3 months", "3–6 months", "6–12 months", "Just starting to look"] },
      { id: "lease_end_date", label: "If renting, when does your lease end?", kind: "date" },
      { id: "important_dates", label: "Any dates I should work around", kind: "textarea" },
    ],
  },
  {
    id: "area", title: "Where you want to be",
    fields: [
      { id: "target_areas", label: "Cities, suburbs or neighbourhoods you are considering", kind: "textarea" },
      { id: "school_district", label: "School district (if it matters)", kind: "text" },
      { id: "commute_to", label: "Commuting to", kind: "text" },
      { id: "max_commute_minutes", label: "Longest acceptable commute (minutes)", kind: "number" },
    ],
  },
  {
    id: "property", title: "The property itself",
    fields: [
      { id: "property_types", label: "Property types you would consider", kind: "multiselect", options: ["Single family", "Condo", "Townhouse", "Duplex", "Multi-family (3–4 unit)"] },
      { id: "beds_min", label: "Minimum bedrooms", kind: "number" },
      { id: "baths_min", label: "Minimum bathrooms", kind: "number" },
      { id: "sqft_min", label: "Minimum square feet", kind: "number" },
      { id: "garage_spaces_min", label: "Garage spaces needed", kind: "number" },
      { id: "basement_preference", label: "Basement", kind: "select", options: ["Must be finished", "Unfinished is fine", "No basement needed", "No preference"] },
      { id: "condition_tolerance", label: "How much work are you willing to take on?", kind: "select", options: ["Move-in ready only", "Light cosmetic (paint, flooring)", "Moderate updating", "Full rehab / project"] },
    ],
  },
  {
    id: "priorities", title: "Priorities",
    fields: [
      { id: "must_haves", label: "Must-haves — a home without these is off the list", kind: "textarea" },
      { id: "deal_breakers", label: "Deal-breakers — things you will not accept", kind: "textarea" },
      { id: "nice_to_haves", label: "Nice-to-haves", kind: "textarea" },
    ],
  },
  {
    id: "household", title: "Household",
    fields: [
      { id: "household_size", label: "How many people will live in the home?", kind: "number", help: "Occupant count only. Family composition is a protected class, and letting it drive area recommendations is steering — tell me your school district or neighbourhood preferences directly instead." },
      { id: "pets", label: "Pets", kind: "text" },
      { id: "occupations", label: "Occupations", kind: "text" },
      { id: "works_from_home", label: "Does anyone work from home?", kind: "boolean" },
    ],
  },
  {
    id: "story", title: "Your story",
    fields: [
      { id: "motivation", label: "What is prompting the move?", kind: "textarea" },
      { id: "past_experience", label: "If you have bought before, what would you do differently?", kind: "textarea" },
      { id: "what_matters_most", label: "If we get one thing right, what should it be?", kind: "textarea" },
    ],
  },
  {
    id: "attribution", title: "How you found me",
    fields: [
      { id: "referral_source", label: "How did you find me?", kind: "select", options: ["Referral from a friend or family member", "Past client", "Website", "Social media", "Open house", "Zillow / Realtor.com", "Other"] },
      { id: "referred_by", label: "Who referred you?", kind: "text", help: "So I can thank them." },
    ],
  },
  {
    id: "consent", title: "Acknowledgements",
    fields: [
      { id: "agency_ack", label: "I understand that submitting this form does not create an agency relationship.", kind: "boolean", required: true },
      { id: "contact_consent", label: "You may contact me by phone, text and email about my home search.", kind: "boolean", required: true },
    ],
  },
];

/* Excluded from the Google Sheet mirror. These stay in Supabase and in the local
 * markdown only -- the sheet is the one surface that gets shared casually. */
export const SENSITIVE_FIELDS: readonly string[] = ["preapproval_amount", "down_payment_amount", "down_payment_source", "credit_range"];

export const AGENCY_NOTICE = "Completing this form does not create an agency relationship. Wisconsin law (Wis. Stat. § 452.135) requires me to provide the Broker Disclosure to Customers at our first substantive contact; representation begins only when a Buyer Agency Agreement (WB-36) is signed.";

export function emptyValues(): Partial<BuyerIntakeValues> {
  return {
    full_name: '',
    cobuyer_name: '',
    email: '',
    cobuyer_email: '',
    phone: '',
    cobuyer_phone: '',
    current_address: '',
    cobuyer_relationship: '',
    preferred_contact: '',
    best_contact_time: [],
    employment_status: '',
    years_employed: '',
    financing_type: '',
    preapproval_status: '',
    lender_name: '',
    preapproval_amount: undefined,
    max_purchase_price: undefined,
    comfortable_max_monthly_payment: undefined,
    down_payment_amount: undefined,
    down_payment_source: '',
    credit_range: '',
    first_time_buyer: false,
    must_sell_first: false,
    target_move_date: '',
    timeline_urgency: '',
    lease_end_date: '',
    important_dates: '',
    target_areas: '',
    school_district: '',
    commute_to: '',
    max_commute_minutes: undefined,
    property_types: [],
    beds_min: undefined,
    baths_min: undefined,
    sqft_min: undefined,
    garage_spaces_min: undefined,
    basement_preference: '',
    condition_tolerance: '',
    must_haves: '',
    deal_breakers: '',
    nice_to_haves: '',
    household_size: undefined,
    pets: '',
    occupations: '',
    works_from_home: false,
    motivation: '',
    past_experience: '',
    what_matters_most: '',
    referral_source: '',
    referred_by: '',
    agency_ack: false,
    contact_consent: false,
  } as never;
}
