/* GENERATED by Engines/Marketing/tools/gen_intake_ts.py -- do not hand-edit.
 * Source: Engines/Marketing/reference/seller_intake_schema.json
 * Form "seller_intake" v1.0.0 -- 70 fields.
 * Regenerate after any schema change so the form, the validator, the printed
 * PDF and the Supabase table cannot drift apart.
 */
import { z } from 'zod';

export const sellerIntakeSchema = z.object({
  property_address: z.string().trim().max(300).min(1, 'Required'),
  home_type: z.literal('').or(z.enum(["Single family", "Multi-family", "Townhouse", "Condo", "Mobile home"])).optional(),
  approx_sqft: z.coerce.number().nonnegative().int().optional(),
  bedrooms: z.coerce.number().nonnegative().int().optional(),
  bathrooms: z.coerce.number().nonnegative().optional(),
  garage_spaces: z.coerce.number().nonnegative().int().optional(),
  year_built: z.coerce.number().nonnegative().int().optional(),
  seller_one_name: z.string().trim().max(300).min(1, 'Required'),
  seller_one_email: z.string().trim().email('Enter a valid email').max(300).min(1, 'Required'),
  seller_one_cell: z.string().trim().min(7, 'Enter a valid phone number').max(300).min(1, 'Required'),
  seller_one_work: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  seller_one_preferred_contact: z.literal('').or(z.enum(["Text", "Call", "Email"])).optional(),
  seller_one_best_time: z.array(z.enum(["Morning", "Afternoon", "Evening"])).max(40).optional(),
  seller_two_name: z.literal('').or(z.string().trim().max(300)).optional(),
  seller_two_email: z.literal('').or(z.string().trim().email('Enter a valid email').max(300)).optional(),
  seller_two_cell: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  seller_two_work: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  seller_two_preferred_contact: z.literal('').or(z.enum(["Text", "Call", "Email"])).optional(),
  seller_two_best_time: z.array(z.enum(["Morning", "Afternoon", "Evening"])).max(40).optional(),
  has_mortgage: z.boolean().optional(),
  payments_current: z.boolean().optional(),
  amount_owed: z.coerce.number().nonnegative().optional(),
  monthly_payment: z.coerce.number().nonnegative().optional(),
  lender_servicer: z.literal('').or(z.string().trim().max(300)).optional(),
  second_heloc_servicer: z.literal('').or(z.string().trim().max(300)).optional(),
  has_hoa: z.boolean().optional(),
  hoa_amount: z.coerce.number().nonnegative().optional(),
  hoa_frequency: z.literal('').or(z.enum(["Monthly", "Quarterly", "Semi-annual", "Annual"])).optional(),
  hoa_name: z.literal('').or(z.string().trim().max(300)).optional(),
  hoa_phone: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  tenant_occupied: z.boolean().optional(),
  monthly_rent: z.coerce.number().nonnegative().optional(),
  monthly_expenses: z.coerce.number().nonnegative().optional(),
  central_air: z.boolean().optional(),
  central_air_age: z.literal('').or(z.string().trim().max(300)).optional(),
  heating_type: z.literal('').or(z.enum(["Gas forced air", "Electric", "Boiler / radiant", "Heat pump", "Other"])).optional(),
  furnace_brand: z.literal('').or(z.string().trim().max(300)).optional(),
  furnace_age: z.literal('').or(z.string().trim().max(300)).optional(),
  furnace_units: z.coerce.number().nonnegative().int().optional(),
  water_heater_brand: z.literal('').or(z.string().trim().max(300)).optional(),
  water_heater_age: z.literal('').or(z.string().trim().max(300)).optional(),
  water_heater_fuel: z.literal('').or(z.enum(["Gas", "Electric"])).optional(),
  avg_heating_cost: z.coerce.number().nonnegative().optional(),
  avg_electric_cost: z.coerce.number().nonnegative().optional(),
  roof_age: z.literal('').or(z.string().trim().max(300)).optional(),
  roof_layers: z.coerce.number().nonnegative().int().optional(),
  roof_warranty: z.boolean().optional(),
  roof_warranty_provider: z.literal('').or(z.string().trim().max(300)).optional(),
  garage_roof_age: z.literal('').or(z.string().trim().max(300)).optional(),
  water_softener: z.boolean().optional(),
  water_softener_owned: z.literal('').or(z.enum(["Owned", "Rented"])).optional(),
  water_softener_age: z.literal('').or(z.string().trim().max(300)).optional(),
  sewer_frequency: z.literal('').or(z.enum(["Monthly", "Quarterly"])).optional(),
  avg_sewer_cost: z.coerce.number().nonnegative().optional(),
  garbage_in_taxes: z.boolean().optional(),
  garbage_company: z.literal('').or(z.string().trim().max(300)).optional(),
  internet_provider: z.literal('').or(z.string().trim().max(300)).optional(),
  improvements: z.array(z.object({ update: z.string().trim().max(300).optional(), year: z.string().trim().max(300).optional(), vendor: z.string().trim().max(300).optional(), cost: z.string().trim().max(300).optional() })).max(40).optional(),
  top_features: z.array(z.string().trim().max(300)).max(40).optional(),
  top_amenities: z.array(z.string().trim().max(300)).max(40).optional(),
  what_you_love: z.literal('').or(z.string().trim().max(4000)).optional(),
  reason_for_selling: z.literal('').or(z.string().trim().max(4000)).optional(),
  additional_comments: z.literal('').or(z.string().trim().max(4000)).optional(),
  marketing_selections: z.array(z.enum(["Yard sign", "Drone photography", "3D virtual tour", "Property video", "Agent in video", "Home warranty", "Pre-listing home inspection", "Open houses"])).max(40).optional(),
  showing_instructions: z.literal('').or(z.string().trim().max(4000)).optional(),
  ideal_move_out: z.literal('').or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD')).optional(),
  buy_before_moving: z.literal('').or(z.enum(["No", "Yes", "Yes — and it is already under contract"])).optional(),
  occupancy_needed: z.boolean().optional(),
  agency_ack: z.boolean().refine((v) => v === true, 'Required'),
  contact_consent: z.boolean().refine((v) => v === true, 'Required'),
});

export type SellerIntakeValues = z.infer<typeof sellerIntakeSchema>;

export interface FieldMeta {
  id: string; label: string; kind: string;
  options?: string[]; required?: boolean; help?: string; sensitive?: boolean;
  columns?: { id: string; label: string }[];
}
export interface FieldGroup {
  id: string; title: string; help?: string; fields: FieldMeta[];
}

/* Rendering order and PDF walk order. Both modes iterate THIS, so the printed
 * packet and the web form cannot present different field sets. */
export const FIELD_GROUPS: FieldGroup[] = [
  {
    id: "property", title: "Property information",
    fields: [
      { id: "property_address", label: "Property address", kind: "text", required: true },
      { id: "home_type", label: "Home type", kind: "select", options: ["Single family", "Multi-family", "Townhouse", "Condo", "Mobile home"] },
      { id: "approx_sqft", label: "Approximate square feet", kind: "number" },
      { id: "bedrooms", label: "Bedrooms", kind: "number" },
      { id: "bathrooms", label: "Bathrooms", kind: "number" },
      { id: "garage_spaces", label: "Garage spaces", kind: "number" },
      { id: "year_built", label: "Year built", kind: "number" },
    ],
  },
  {
    id: "sellers", title: "Seller information",
    fields: [
      { id: "seller_one_name", label: "Seller one — name", kind: "text", required: true },
      { id: "seller_one_email", label: "Seller one — email", kind: "email", required: true },
      { id: "seller_one_cell", label: "Seller one — cell phone", kind: "tel", required: true },
      { id: "seller_one_work", label: "Seller one — work phone", kind: "tel" },
      { id: "seller_one_preferred_contact", label: "Seller one — preferred contact", kind: "select", options: ["Text", "Call", "Email"] },
      { id: "seller_one_best_time", label: "Seller one — best time to reach", kind: "multiselect", options: ["Morning", "Afternoon", "Evening"] },
      { id: "seller_two_name", label: "Seller two — name", kind: "text" },
      { id: "seller_two_email", label: "Seller two — email", kind: "email" },
      { id: "seller_two_cell", label: "Seller two — cell phone", kind: "tel" },
      { id: "seller_two_work", label: "Seller two — work phone", kind: "tel" },
      { id: "seller_two_preferred_contact", label: "Seller two — preferred contact", kind: "select", options: ["Text", "Call", "Email"] },
      { id: "seller_two_best_time", label: "Seller two — best time to reach", kind: "multiselect", options: ["Morning", "Afternoon", "Evening"] },
    ],
  },
  {
    id: "mortgage", title: "Mortgage",
    help: "Used to estimate your net proceeds. Kept internal — never published.",
    fields: [
      { id: "has_mortgage", label: "Is there a mortgage on the home?", kind: "boolean" },
      { id: "payments_current", label: "Are you current on all payments?", kind: "boolean", sensitive: true },
      { id: "amount_owed", label: "Approximate amount still owed", kind: "money", sensitive: true },
      { id: "monthly_payment", label: "Monthly mortgage payment", kind: "money", sensitive: true },
      { id: "lender_servicer", label: "Lender / servicer", kind: "text", sensitive: true },
      { id: "second_heloc_servicer", label: "Second mortgage or HELOC servicer", kind: "text", sensitive: true },
    ],
  },
  {
    id: "hoa", title: "Association / rental",
    fields: [
      { id: "has_hoa", label: "Is the property part of an association?", kind: "boolean" },
      { id: "hoa_amount", label: "Association dues", kind: "money" },
      { id: "hoa_frequency", label: "Dues frequency", kind: "select", options: ["Monthly", "Quarterly", "Semi-annual", "Annual"] },
      { id: "hoa_name", label: "Association name", kind: "text" },
      { id: "hoa_phone", label: "Association phone", kind: "tel" },
      { id: "tenant_occupied", label: "Is the property tenant occupied?", kind: "boolean" },
      { id: "monthly_rent", label: "Monthly rent received", kind: "money" },
      { id: "monthly_expenses", label: "Monthly expenses", kind: "money" },
    ],
  },
  {
    id: "systems", title: "Heating, cooling and utilities",
    help: "Ages and brands feed both the MLS listing and the condition report.",
    fields: [
      { id: "central_air", label: "Central air conditioning?", kind: "boolean" },
      { id: "central_air_age", label: "Age of A/C", kind: "text" },
      { id: "heating_type", label: "Type of heating", kind: "select", options: ["Gas forced air", "Electric", "Boiler / radiant", "Heat pump", "Other"] },
      { id: "furnace_brand", label: "Furnace brand", kind: "text" },
      { id: "furnace_age", label: "Furnace age", kind: "text" },
      { id: "furnace_units", label: "Number of heating units", kind: "number" },
      { id: "water_heater_brand", label: "Water heater brand", kind: "text" },
      { id: "water_heater_age", label: "Water heater age", kind: "text" },
      { id: "water_heater_fuel", label: "Water heater fuel", kind: "select", options: ["Gas", "Electric"] },
      { id: "avg_heating_cost", label: "Average monthly heating cost", kind: "money" },
      { id: "avg_electric_cost", label: "Average monthly electric cost", kind: "money" },
    ],
  },
  {
    id: "roof_utility", title: "Roof, water and services",
    fields: [
      { id: "roof_age", label: "Age of home roof", kind: "text" },
      { id: "roof_layers", label: "Number of roof layers", kind: "number" },
      { id: "roof_warranty", label: "Is there a roof warranty?", kind: "boolean" },
      { id: "roof_warranty_provider", label: "Warranty provider", kind: "text" },
      { id: "garage_roof_age", label: "Age of garage roof", kind: "text" },
      { id: "water_softener", label: "Water softener?", kind: "boolean" },
      { id: "water_softener_owned", label: "Softener owned or rented", kind: "select", options: ["Owned", "Rented"] },
      { id: "water_softener_age", label: "Softener age", kind: "text" },
      { id: "sewer_frequency", label: "Sewer billing frequency", kind: "select", options: ["Monthly", "Quarterly"] },
      { id: "avg_sewer_cost", label: "Average sewer cost", kind: "money" },
      { id: "garbage_in_taxes", label: "Is garbage pick-up included in taxes?", kind: "boolean" },
      { id: "garbage_company", label: "Garbage company", kind: "text" },
      { id: "internet_provider", label: "Cable / internet provider", kind: "text" },
    ],
  },
  {
    id: "improvements", title: "Improvements made",
    fields: [
      { id: "improvements", label: "Improvements, updates and repairs", kind: "repeating", help: "Anything you have replaced or updated. Receipts help — these justify price and pre-empt inspection questions.", columns: [{ id: "update", label: "Update" }, { id: "year", label: "Year" }, { id: "vendor", label: "Company / who did it" }, { id: "cost", label: "Cost" }] },
    ],
  },
  {
    id: "features", title: "Features and amenities",
    fields: [
      { id: "top_features", label: "Top features of the home", kind: "list", help: "The five things you would point out on a tour." },
      { id: "top_amenities", label: "Top neighbourhood amenities", kind: "list", help: "Parks, schools, restaurants, commute — what makes the location worth paying for." },
    ],
  },
  {
    id: "story", title: "Your story",
    fields: [
      { id: "what_you_love", label: "What do you love about your home?", kind: "textarea", help: "This is where listing copy comes from. Write it the way you would tell a friend." },
      { id: "reason_for_selling", label: "Reason for selling (optional)", kind: "textarea" },
      { id: "additional_comments", label: "Anything else I should know", kind: "textarea" },
    ],
  },
  {
    id: "marketing", title: "Marketing selections",
    fields: [
      { id: "marketing_selections", label: "Marketing you want included", kind: "multiselect", options: ["Yard sign", "Drone photography", "3D virtual tour", "Property video", "Agent in video", "Home warranty", "Pre-listing home inspection", "Open houses"] },
      { id: "showing_instructions", label: "Showing instructions and access notes", kind: "textarea" },
    ],
  },
  {
    id: "logistics", title: "Move logistics",
    fields: [
      { id: "ideal_move_out", label: "Ideal move-out date", kind: "date" },
      { id: "buy_before_moving", label: "Will you need to buy another home before moving?", kind: "select", options: ["No", "Yes", "Yes — and it is already under contract"] },
      { id: "occupancy_needed", label: "Do you need occupancy after closing?", kind: "boolean", help: "If yes we will plan for Addendum O rather than negotiate it late." },
    ],
  },
  {
    id: "consent", title: "Acknowledgements",
    fields: [
      { id: "agency_ack", label: "I understand that submitting this form does not create an agency relationship.", kind: "boolean", required: true },
      { id: "contact_consent", label: "You may contact me by phone, text and email about the sale of my home.", kind: "boolean", required: true },
    ],
  },
];

/* Excluded from the Google Sheet mirror. These stay in Supabase and in the local
 * markdown only -- the sheet is the one surface that gets shared casually. */
export const SENSITIVE_FIELDS: readonly string[] = ["payments_current", "amount_owed", "monthly_payment", "lender_servicer", "second_heloc_servicer"];

export const AGENCY_NOTICE = "Completing this form does not create an agency relationship. Wisconsin law (Wis. Stat. § 452.135) requires me to provide the Broker Disclosure to Customers at our first substantive contact; representation begins only when a Listing Contract (WB-1) is signed. Your answers here also help you complete the Real Estate Condition Report, which is your disclosure to make — I cannot make it for you.";

export function emptyValues(): Partial<SellerIntakeValues> {
  return {
    property_address: '',
    home_type: '',
    approx_sqft: undefined,
    bedrooms: undefined,
    bathrooms: undefined,
    garage_spaces: undefined,
    year_built: undefined,
    seller_one_name: '',
    seller_one_email: '',
    seller_one_cell: '',
    seller_one_work: '',
    seller_one_preferred_contact: '',
    seller_one_best_time: [],
    seller_two_name: '',
    seller_two_email: '',
    seller_two_cell: '',
    seller_two_work: '',
    seller_two_preferred_contact: '',
    seller_two_best_time: [],
    has_mortgage: false,
    payments_current: false,
    amount_owed: undefined,
    monthly_payment: undefined,
    lender_servicer: '',
    second_heloc_servicer: '',
    has_hoa: false,
    hoa_amount: undefined,
    hoa_frequency: '',
    hoa_name: '',
    hoa_phone: '',
    tenant_occupied: false,
    monthly_rent: undefined,
    monthly_expenses: undefined,
    central_air: false,
    central_air_age: '',
    heating_type: '',
    furnace_brand: '',
    furnace_age: '',
    furnace_units: undefined,
    water_heater_brand: '',
    water_heater_age: '',
    water_heater_fuel: '',
    avg_heating_cost: undefined,
    avg_electric_cost: undefined,
    roof_age: '',
    roof_layers: undefined,
    roof_warranty: false,
    roof_warranty_provider: '',
    garage_roof_age: '',
    water_softener: false,
    water_softener_owned: '',
    water_softener_age: '',
    sewer_frequency: '',
    avg_sewer_cost: undefined,
    garbage_in_taxes: false,
    garbage_company: '',
    internet_provider: '',
    improvements: [],
    top_features: [],
    top_amenities: [],
    what_you_love: '',
    reason_for_selling: '',
    additional_comments: '',
    marketing_selections: [],
    showing_instructions: '',
    ideal_move_out: '',
    buy_before_moving: '',
    occupancy_needed: false,
    agency_ack: false,
    contact_consent: false,
  } as never;
}
