/* GENERATED by Engines/Marketing/tools/gen_intake_ts.py -- do not hand-edit.
 * Source: Engines/Marketing/reference/tenant_intake_schema.json
 * Form "tenant_intake" v1.0.0 -- 62 fields.
 * Regenerate after any schema change so the form, the validator, the printed
 * PDF and the Supabase table cannot drift apart.
 */
import { z } from 'zod';

export const tenantIntakeSchema = z.object({
  full_name: z.string().trim().max(300).min(1, 'Required'),
  email: z.string().trim().email('Enter a valid email').max(300).min(1, 'Required'),
  phone: z.string().trim().min(7, 'Enter a valid phone number').max(300).min(1, 'Required'),
  current_address: z.literal('').or(z.string().trim().max(300)).optional(),
  preferred_contact: z.literal('').or(z.enum(["Text", "Call", "Email"])).optional(),
  best_contact_time: z.array(z.enum(["Morning", "Afternoon", "Evening"])).max(40).optional(),
  occupant_count: z.coerce.number().nonnegative().int(),
  coapplicant_name: z.literal('').or(z.string().trim().max(300)).optional(),
  coapplicant_email: z.literal('').or(z.string().trim().email('Enter a valid email').max(300)).optional(),
  coapplicant_phone: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  coapplicant_relationship: z.literal('').or(z.string().trim().max(300)).optional(),
  target_areas: z.literal('').or(z.string().trim().max(4000)).optional(),
  commute_to: z.literal('').or(z.string().trim().max(300)).optional(),
  max_commute_minutes: z.coerce.number().nonnegative().int().optional(),
  max_monthly_rent: z.coerce.number().nonnegative(),
  rent_includes_utilities: z.literal('').or(z.enum(["Yes — that is my all-in ceiling", "No — I can pay utilities on top", "Not sure"])).optional(),
  move_in_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD'),
  date_flexibility: z.literal('').or(z.enum(["Firm", "Within 2 weeks", "Within a month", "Very flexible"])).optional(),
  lease_length: z.literal('').or(z.enum(["Month-to-month", "6 months", "12 months", "18+ months", "Flexible"])).optional(),
  property_types: z.array(z.enum(["Apartment", "Duplex / lower or upper", "House", "Townhouse", "Condo"])).max(40).optional(),
  beds_min: z.coerce.number().nonnegative().int().optional(),
  baths_min: z.coerce.number().nonnegative().optional(),
  sqft_min: z.coerce.number().nonnegative().int().optional(),
  parking: z.literal('').or(z.enum(["Garage", "Off-street / driveway", "Street parking is fine", "None needed"])).optional(),
  laundry: z.literal('').or(z.enum(["In unit", "Hook-ups in unit", "On site / shared", "Not needed"])).optional(),
  air_conditioning: z.boolean().optional(),
  outdoor_space: z.array(z.enum(["Yard", "Balcony or deck", "Patio", "Not needed"])).max(40).optional(),
  storage_needed: z.literal('').or(z.string().trim().max(300)).optional(),
  furnished: z.boolean().optional(),
  accessibility_needs: z.literal('').or(z.string().trim().max(4000)).optional(),
  has_pets: z.boolean().optional(),
  pet_count: z.coerce.number().nonnegative().int().optional(),
  pet_type: z.literal('').or(z.string().trim().max(300)).optional(),
  pet_breed: z.literal('').or(z.string().trim().max(300)).optional(),
  pet_weight: z.literal('').or(z.string().trim().max(300)).optional(),
  pet_age: z.literal('').or(z.string().trim().max(300)).optional(),
  pet_reference: z.literal('').or(z.string().trim().max(300)).optional(),
  assistance_animal: z.boolean().optional(),
  gross_monthly_income: z.coerce.number().nonnegative().optional(),
  employment_status: z.literal('').or(z.enum(["Employed full time", "Employed part time", "Self-employed", "Student", "Retired", "Between jobs"])).optional(),
  employer: z.literal('').or(z.string().trim().max(300)).optional(),
  time_at_employer: z.literal('').or(z.string().trim().max(300)).optional(),
  additional_income: z.literal('').or(z.string().trim().max(300)).optional(),
  credit_range: z.literal('').or(z.enum(["Below 580", "580-619", "620-679", "680-739", "740+", "Not sure"])).optional(),
  cosigner_available: z.boolean().optional(),
  rental_assistance: z.boolean().optional(),
  current_housing: z.literal('').or(z.enum(["Renting", "Own my home", "Living with family or friends", "Other"])).optional(),
  current_rent: z.coerce.number().nonnegative().optional(),
  time_at_current: z.literal('').or(z.string().trim().max(300)).optional(),
  current_landlord_name: z.literal('').or(z.string().trim().max(300)).optional(),
  current_landlord_phone: z.literal('').or(z.string().trim().min(7, 'Enter a valid phone number').max(300)).optional(),
  prior_address: z.literal('').or(z.string().trim().max(4000)).optional(),
  reason_for_moving: z.literal('').or(z.string().trim().max(4000)).optional(),
  landlord_contact_ok: z.boolean().optional(),
  deposit_ready: z.boolean().optional(),
  docs_ready: z.array(z.enum(["Recent pay stubs", "Photo ID", "Offer letter", "Bank statements", "Previous lease", "None of these yet"])).max(40).optional(),
  tour_availability: z.literal('').or(z.string().trim().max(4000)).optional(),
  must_haves: z.literal('').or(z.string().trim().max(4000)).optional(),
  deal_breakers: z.literal('').or(z.string().trim().max(4000)).optional(),
  other_notes: z.literal('').or(z.string().trim().max(4000)).optional(),
  agency_ack: z.boolean().refine((v) => v === true, 'Required'),
  contact_consent: z.boolean().refine((v) => v === true, 'Required'),
});

export type TenantIntakeValues = z.infer<typeof tenantIntakeSchema>;

export interface FieldMeta {
  id: string; label: string; kind: string;
  options?: string[]; required?: boolean; help?: string; sensitive?: boolean;
  columns?: { id: string; label: string }[];
}
export interface FieldGroup {
  id: string; title: string; help?: string; fields: FieldMeta[];
}

/* Rendering order and PDF walk order. Both modes iterate THIS, so the printed
 * packet and the web form cannot present different field sets. */
export const FIELD_GROUPS: FieldGroup[] = [
  {
    id: "contact", title: "Your contact information",
    fields: [
      { id: "full_name", label: "Full name", kind: "text", required: true },
      { id: "email", label: "Email", kind: "email", required: true },
      { id: "phone", label: "Cell phone", kind: "tel", required: true },
      { id: "current_address", label: "Current address", kind: "text" },
      { id: "preferred_contact", label: "Preferred contact method", kind: "select", options: ["Text", "Call", "Email"] },
      { id: "best_contact_time", label: "Best time to reach you", kind: "multiselect", options: ["Morning", "Afternoon", "Evening"] },
    ],
  },
  {
    id: "occupants", title: "Who is moving in",
    help: "Occupant count only. I do not ask about marital or family status — both are protected under Wisconsin law.",
    fields: [
      { id: "occupant_count", label: "How many people will live in the unit?", kind: "number", required: true },
      { id: "coapplicant_name", label: "Co-applicant name", kind: "text", help: "Anyone else who will be named on the lease." },
      { id: "coapplicant_email", label: "Co-applicant email", kind: "email" },
      { id: "coapplicant_phone", label: "Co-applicant phone", kind: "tel" },
      { id: "coapplicant_relationship", label: "Co-applicant relationship to you", kind: "text" },
    ],
  },
  {
    id: "search", title: "The rental you want",
    fields: [
      { id: "target_areas", label: "Cities, suburbs or neighbourhoods you are considering", kind: "textarea" },
      { id: "commute_to", label: "Commuting to", kind: "text" },
      { id: "max_commute_minutes", label: "Longest acceptable commute (minutes)", kind: "number" },
      { id: "max_monthly_rent", label: "Maximum monthly rent", kind: "money", required: true },
      { id: "rent_includes_utilities", label: "Does that figure assume utilities are included?", kind: "select", options: ["Yes — that is my all-in ceiling", "No — I can pay utilities on top", "Not sure"], help: "Heat alone can swing a Milwaukee winter budget by a couple of hundred a month, so this changes which units actually fit." },
      { id: "move_in_date", label: "Ideal move-in date", kind: "date", required: true },
      { id: "date_flexibility", label: "How flexible is that date?", kind: "select", options: ["Firm", "Within 2 weeks", "Within a month", "Very flexible"] },
      { id: "lease_length", label: "Lease length you want", kind: "select", options: ["Month-to-month", "6 months", "12 months", "18+ months", "Flexible"] },
    ],
  },
  {
    id: "unit", title: "Unit requirements",
    fields: [
      { id: "property_types", label: "Property types you would consider", kind: "multiselect", options: ["Apartment", "Duplex / lower or upper", "House", "Townhouse", "Condo"] },
      { id: "beds_min", label: "Minimum bedrooms", kind: "number" },
      { id: "baths_min", label: "Minimum bathrooms", kind: "number" },
      { id: "sqft_min", label: "Minimum square feet", kind: "number" },
      { id: "parking", label: "Parking needed", kind: "select", options: ["Garage", "Off-street / driveway", "Street parking is fine", "None needed"] },
      { id: "laundry", label: "Laundry", kind: "select", options: ["In unit", "Hook-ups in unit", "On site / shared", "Not needed"] },
      { id: "air_conditioning", label: "Is air conditioning required?", kind: "boolean" },
      { id: "outdoor_space", label: "Outdoor space wanted", kind: "multiselect", options: ["Yard", "Balcony or deck", "Patio", "Not needed"] },
      { id: "storage_needed", label: "Storage needed (basement, locker, garage)", kind: "text" },
      { id: "furnished", label: "Do you need it furnished?", kind: "boolean" },
      { id: "accessibility_needs", label: "Accessibility needs — ground floor, no stairs, wider doorways", kind: "textarea", help: "Answer only if useful to your search. Disability is a protected class and this is never used to screen you." },
    ],
  },
  {
    id: "animals", title: "Animals",
    fields: [
      { id: "has_pets", label: "Do you have pets?", kind: "boolean" },
      { id: "pet_count", label: "How many", kind: "number" },
      { id: "pet_type", label: "Type(s)", kind: "text" },
      { id: "pet_breed", label: "Breed(s)", kind: "text", help: "Many landlords and their insurers apply breed restrictions. Knowing now avoids a wasted application fee." },
      { id: "pet_weight", label: "Approximate weight(s)", kind: "text" },
      { id: "pet_age", label: "Age(s)", kind: "text" },
      { id: "pet_reference", label: "Vet or previous-landlord pet reference", kind: "text" },
      { id: "assistance_animal", label: "Do you have a service animal or emotional-support animal?", kind: "boolean", help: "Asked separately and on purpose: an assistance animal is NOT a pet. It cannot be charged pet rent or a pet deposit, and is not subject to breed or weight restrictions. Answer only if you wish to." },
    ],
  },
  {
    id: "qualifying", title: "Qualifying",
    help: "Most landlords look for gross income around three times the rent. Knowing these now means I can tell you what you will be approved for instead of finding out after we tour.",
    fields: [
      { id: "gross_monthly_income", label: "Gross monthly household income (before tax)", kind: "money", sensitive: true },
      { id: "employment_status", label: "Employment status", kind: "select", options: ["Employed full time", "Employed part time", "Self-employed", "Student", "Retired", "Between jobs"] },
      { id: "employer", label: "Employer", kind: "text", sensitive: true },
      { id: "time_at_employer", label: "How long there?", kind: "text" },
      { id: "additional_income", label: "Any additional income you want counted", kind: "text", sensitive: true },
      { id: "credit_range", label: "Approximate credit score range", kind: "select", options: ["Below 580", "580-619", "620-679", "680-739", "740+", "Not sure"], sensitive: true, help: "A range is enough. I never ask for your Social Security number or date of birth — landlords run their own checks." },
      { id: "cosigner_available", label: "Could you provide a co-signer or guarantor if a landlord asked?", kind: "boolean" },
      { id: "rental_assistance", label: "Will you use a housing voucher or rental assistance?", kind: "boolean", help: "Recorded so I only show you units whose landlords participate. Lawful source of income is a protected class in Wisconsin — this is never used to exclude you." },
    ],
  },
  {
    id: "history", title: "Rental history",
    fields: [
      { id: "current_housing", label: "Current housing situation", kind: "select", options: ["Renting", "Own my home", "Living with family or friends", "Other"] },
      { id: "current_rent", label: "What do you pay now?", kind: "money" },
      { id: "time_at_current", label: "How long at your current address?", kind: "text" },
      { id: "current_landlord_name", label: "Current landlord name", kind: "text" },
      { id: "current_landlord_phone", label: "Current landlord phone", kind: "tel" },
      { id: "prior_address", label: "Previous address, if less than two years at your current one", kind: "textarea" },
      { id: "reason_for_moving", label: "Reason for moving", kind: "textarea" },
      { id: "landlord_contact_ok", label: "May a prospective landlord contact your current or previous landlord?", kind: "boolean" },
    ],
  },
  {
    id: "readiness", title: "Readiness to apply",
    fields: [
      { id: "deposit_ready", label: "Do you have first month's rent and a security deposit available?", kind: "boolean" },
      { id: "docs_ready", label: "Which documents could you produce within 24 hours?", kind: "multiselect", options: ["Recent pay stubs", "Photo ID", "Offer letter", "Bank statements", "Previous lease", "None of these yet"] },
      { id: "tour_availability", label: "When are you generally free to tour?", kind: "textarea" },
    ],
  },
  {
    id: "priorities", title: "Priorities",
    fields: [
      { id: "must_haves", label: "Must-haves — a unit without these is off the list", kind: "textarea" },
      { id: "deal_breakers", label: "Deal-breakers", kind: "textarea" },
      { id: "other_notes", label: "Anything else I should know", kind: "textarea" },
    ],
  },
  {
    id: "consent", title: "Acknowledgements",
    fields: [
      { id: "agency_ack", label: "I understand that submitting this form does not create an agency relationship.", kind: "boolean", required: true },
      { id: "contact_consent", label: "You may contact me by phone, text and email about my rental search.", kind: "boolean", required: true },
    ],
  },
];

/* Excluded from the Google Sheet mirror. These stay in Supabase and in the local
 * markdown only -- the sheet is the one surface that gets shared casually. */
export const SENSITIVE_FIELDS: readonly string[] = ["gross_monthly_income", "employer", "additional_income", "credit_range"];

export const AGENCY_NOTICE = "Completing this form does not create an agency relationship. Wisconsin law (Wis. Stat. § 452.135) requires me to provide the Broker Disclosure to Customers at our first substantive contact; representation begins only when a Tenant Representation Agreement (WB-39) is signed. Wisconsin's Open Housing Law (Wis. Stat. § 106.50) prohibits discrimination on the basis of race, colour, religion, sex, national origin, ancestry, age, disability, marital status, family status, lawful source of income, or status as a victim of domestic abuse, sexual assault or stalking. Nothing on this form is used to screen you out on any of those grounds.";

export function emptyValues(): Partial<TenantIntakeValues> {
  return {
    full_name: '',
    email: '',
    phone: '',
    current_address: '',
    preferred_contact: '',
    best_contact_time: [],
    occupant_count: undefined,
    coapplicant_name: '',
    coapplicant_email: '',
    coapplicant_phone: '',
    coapplicant_relationship: '',
    target_areas: '',
    commute_to: '',
    max_commute_minutes: undefined,
    max_monthly_rent: undefined,
    rent_includes_utilities: '',
    move_in_date: '',
    date_flexibility: '',
    lease_length: '',
    property_types: [],
    beds_min: undefined,
    baths_min: undefined,
    sqft_min: undefined,
    parking: '',
    laundry: '',
    air_conditioning: false,
    outdoor_space: [],
    storage_needed: '',
    furnished: false,
    accessibility_needs: '',
    has_pets: false,
    pet_count: undefined,
    pet_type: '',
    pet_breed: '',
    pet_weight: '',
    pet_age: '',
    pet_reference: '',
    assistance_animal: false,
    gross_monthly_income: undefined,
    employment_status: '',
    employer: '',
    time_at_employer: '',
    additional_income: '',
    credit_range: '',
    cosigner_available: false,
    rental_assistance: false,
    current_housing: '',
    current_rent: undefined,
    time_at_current: '',
    current_landlord_name: '',
    current_landlord_phone: '',
    prior_address: '',
    reason_for_moving: '',
    landlord_contact_ok: false,
    deposit_ready: false,
    docs_ready: [],
    tour_availability: '',
    must_haves: '',
    deal_breakers: '',
    other_notes: '',
    agency_ack: false,
    contact_consent: false,
  } as never;
}
