-- Intake tables for the buyer, seller and tenant forms.
-- GENERATED by Engines/Marketing/tools/gen_supabase_migration.py -- do not hand-edit;
-- change the JSON schema and regenerate, or the form and the table will drift.

begin;

-- ---------------------------------------------------------------------------
-- public.leads
-- Created here too, so this file stands alone in a FRESH project. The original
-- leads table lives in a Lovable-provisioned project Lucas does not own; when
-- the site is repointed at his own project the table has to exist on arrival or
-- the guide-download form starts throwing on every submission.
-- `if not exists` keeps it safe to run against the old project too.
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  full_name   text not null,
  email       text not null,
  timeline    text
);

alter table public.leads enable row level security;
revoke all on public.leads from anon, authenticated;
grant insert on public.leads to anon;

drop policy if exists "anon may submit leads" on public.leads;
create policy "anon may submit leads"
  on public.leads for insert to anon
  with check (
    char_length(full_name) <= 300 and char_length(email) <= 300
    and (timeline is null or char_length(timeline) <= 300)
  );

-- ---------------------------------------------------------------------------
-- public.buyer_intakes -- from buyer_intake_schema.json v1.0.0 (53 fields)
-- PII boundary: preapproval_amount, down_payment_amount, down_payment_source, credit_range
-- must stay out of the Google Sheet mirror; Supabase + local markdown only.
-- ---------------------------------------------------------------------------
create table if not exists public.buyer_intakes (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  full_name                        text,
  cobuyer_name                     text,
  email                            text,
  cobuyer_email                    text,
  phone                            text,
  cobuyer_phone                    text,
  current_address                  text,
  cobuyer_relationship             text,
  preferred_contact                text,
  best_contact_time                text[],
  employment_status                text,
  years_employed                   text,
  financing_type                   text,
  preapproval_status               text,
  lender_name                      text,
  preapproval_amount               numeric(12,2),
  max_purchase_price               numeric(12,2),
  comfortable_max_monthly_payment  numeric(12,2),
  down_payment_amount              numeric(12,2),
  down_payment_source              text,
  credit_range                     text,
  first_time_buyer                 boolean,
  must_sell_first                  boolean,
  target_move_date                 date,
  timeline_urgency                 text,
  lease_end_date                   date,
  important_dates                  text,
  target_areas                     text,
  school_district                  text,
  commute_to                       text,
  max_commute_minutes              integer,
  property_types                   text[],
  home_style                       text[],
  beds_min                         integer,
  baths_min                        numeric(6,1),
  sqft_min                         integer,
  garage_spaces_min                integer,
  basement_preference              text,
  condition_tolerance              text,
  must_haves                       text,
  deal_breakers                    text,
  nice_to_haves                    text,
  household_size                   integer,
  pets                             text,
  occupations                      text,
  works_from_home                  boolean,
  motivation                       text,
  past_experience                  text,
  what_matters_most                text,
  referral_source                  text,
  referred_by                      text,
  agency_ack                       boolean,
  contact_consent                  boolean
);

comment on table public.buyer_intakes is
  'Write-only intake capture. Generated from buyer_intake_schema.json. No SELECT policy by design.';

alter table public.buyer_intakes enable row level security;
revoke all on public.buyer_intakes from anon, authenticated;
grant insert on public.buyer_intakes to anon;

drop policy if exists "anon may submit buyer_intakes" on public.buyer_intakes;
create policy "anon may submit buyer_intakes"
  on public.buyer_intakes for insert to anon
  with check (
    (full_name is null or char_length(full_name) <= 300) and
    (cobuyer_name is null or char_length(cobuyer_name) <= 300) and
    (email is null or char_length(email) <= 300) and
    (cobuyer_email is null or char_length(cobuyer_email) <= 300) and
    (phone is null or char_length(phone) <= 300) and
    (cobuyer_phone is null or char_length(cobuyer_phone) <= 300) and
    (current_address is null or char_length(current_address) <= 300) and
    (cobuyer_relationship is null or char_length(cobuyer_relationship) <= 300) and
    (preferred_contact is null or char_length(preferred_contact) <= 300) and
    (best_contact_time is null or array_length(best_contact_time, 1) <= 40) and
    (employment_status is null or char_length(employment_status) <= 300) and
    (years_employed is null or char_length(years_employed) <= 300) and
    (financing_type is null or char_length(financing_type) <= 300) and
    (preapproval_status is null or char_length(preapproval_status) <= 300) and
    (lender_name is null or char_length(lender_name) <= 300) and
    (down_payment_source is null or char_length(down_payment_source) <= 300) and
    (credit_range is null or char_length(credit_range) <= 300) and
    (timeline_urgency is null or char_length(timeline_urgency) <= 300) and
    (important_dates is null or char_length(important_dates) <= 4000) and
    (target_areas is null or char_length(target_areas) <= 4000) and
    (school_district is null or char_length(school_district) <= 300) and
    (commute_to is null or char_length(commute_to) <= 300) and
    (property_types is null or array_length(property_types, 1) <= 40) and
    (home_style is null or array_length(home_style, 1) <= 40) and
    (basement_preference is null or char_length(basement_preference) <= 300) and
    (condition_tolerance is null or char_length(condition_tolerance) <= 300) and
    (must_haves is null or char_length(must_haves) <= 4000) and
    (deal_breakers is null or char_length(deal_breakers) <= 4000) and
    (nice_to_haves is null or char_length(nice_to_haves) <= 4000) and
    (pets is null or char_length(pets) <= 300) and
    (occupations is null or char_length(occupations) <= 300) and
    (motivation is null or char_length(motivation) <= 4000) and
    (past_experience is null or char_length(past_experience) <= 4000) and
    (what_matters_most is null or char_length(what_matters_most) <= 4000) and
    (referral_source is null or char_length(referral_source) <= 300) and
    (referred_by is null or char_length(referred_by) <= 300)
  );

-- Deliberately no select / update / delete policy. Reading happens with the
-- service role key, from Realtor OS, never from the browser bundle.

-- ---------------------------------------------------------------------------
-- public.seller_intakes -- from seller_intake_schema.json v1.0.0 (70 fields)
-- PII boundary: payments_current, amount_owed, monthly_payment, lender_servicer, second_heloc_servicer
-- must stay out of the Google Sheet mirror; Supabase + local markdown only.
-- ---------------------------------------------------------------------------
create table if not exists public.seller_intakes (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  property_address              text,
  home_type                     text,
  approx_sqft                   integer,
  bedrooms                      integer,
  bathrooms                     numeric(6,1),
  garage_spaces                 integer,
  year_built                    integer,
  seller_one_name               text,
  seller_one_email              text,
  seller_one_cell               text,
  seller_one_work               text,
  seller_one_preferred_contact  text,
  seller_one_best_time          text[],
  seller_two_name               text,
  seller_two_email              text,
  seller_two_cell               text,
  seller_two_work               text,
  seller_two_preferred_contact  text,
  seller_two_best_time          text[],
  has_mortgage                  boolean,
  payments_current              boolean,
  amount_owed                   numeric(12,2),
  monthly_payment               numeric(12,2),
  lender_servicer               text,
  second_heloc_servicer         text,
  has_hoa                       boolean,
  hoa_amount                    numeric(12,2),
  hoa_frequency                 text,
  hoa_name                      text,
  hoa_phone                     text,
  tenant_occupied               boolean,
  monthly_rent                  numeric(12,2),
  monthly_expenses              numeric(12,2),
  central_air                   boolean,
  central_air_age               text,
  heating_type                  text,
  furnace_brand                 text,
  furnace_age                   text,
  furnace_units                 integer,
  water_heater_brand            text,
  water_heater_age              text,
  water_heater_fuel             text,
  avg_heating_cost              numeric(12,2),
  avg_electric_cost             numeric(12,2),
  roof_age                      text,
  roof_layers                   integer,
  roof_warranty                 boolean,
  roof_warranty_provider        text,
  garage_roof_age               text,
  water_softener                boolean,
  water_softener_owned          text,
  water_softener_age            text,
  sewer_frequency               text,
  avg_sewer_cost                numeric(12,2),
  garbage_in_taxes              boolean,
  garbage_company               text,
  internet_provider             text,
  improvements                  jsonb,
  top_features                  text[],
  top_amenities                 text[],
  what_you_love                 text,
  reason_for_selling            text,
  additional_comments           text,
  marketing_selections          text[],
  showing_instructions          text,
  ideal_move_out                date,
  buy_before_moving             text,
  occupancy_needed              boolean,
  agency_ack                    boolean,
  contact_consent               boolean
);

comment on table public.seller_intakes is
  'Write-only intake capture. Generated from seller_intake_schema.json. No SELECT policy by design.';

alter table public.seller_intakes enable row level security;
revoke all on public.seller_intakes from anon, authenticated;
grant insert on public.seller_intakes to anon;

drop policy if exists "anon may submit seller_intakes" on public.seller_intakes;
create policy "anon may submit seller_intakes"
  on public.seller_intakes for insert to anon
  with check (
    (property_address is null or char_length(property_address) <= 300) and
    (home_type is null or char_length(home_type) <= 300) and
    (seller_one_name is null or char_length(seller_one_name) <= 300) and
    (seller_one_email is null or char_length(seller_one_email) <= 300) and
    (seller_one_cell is null or char_length(seller_one_cell) <= 300) and
    (seller_one_work is null or char_length(seller_one_work) <= 300) and
    (seller_one_preferred_contact is null or char_length(seller_one_preferred_contact) <= 300) and
    (seller_one_best_time is null or array_length(seller_one_best_time, 1) <= 40) and
    (seller_two_name is null or char_length(seller_two_name) <= 300) and
    (seller_two_email is null or char_length(seller_two_email) <= 300) and
    (seller_two_cell is null or char_length(seller_two_cell) <= 300) and
    (seller_two_work is null or char_length(seller_two_work) <= 300) and
    (seller_two_preferred_contact is null or char_length(seller_two_preferred_contact) <= 300) and
    (seller_two_best_time is null or array_length(seller_two_best_time, 1) <= 40) and
    (lender_servicer is null or char_length(lender_servicer) <= 300) and
    (second_heloc_servicer is null or char_length(second_heloc_servicer) <= 300) and
    (hoa_frequency is null or char_length(hoa_frequency) <= 300) and
    (hoa_name is null or char_length(hoa_name) <= 300) and
    (hoa_phone is null or char_length(hoa_phone) <= 300) and
    (central_air_age is null or char_length(central_air_age) <= 300) and
    (heating_type is null or char_length(heating_type) <= 300) and
    (furnace_brand is null or char_length(furnace_brand) <= 300) and
    (furnace_age is null or char_length(furnace_age) <= 300) and
    (water_heater_brand is null or char_length(water_heater_brand) <= 300) and
    (water_heater_age is null or char_length(water_heater_age) <= 300) and
    (water_heater_fuel is null or char_length(water_heater_fuel) <= 300) and
    (roof_age is null or char_length(roof_age) <= 300) and
    (roof_warranty_provider is null or char_length(roof_warranty_provider) <= 300) and
    (garage_roof_age is null or char_length(garage_roof_age) <= 300) and
    (water_softener_owned is null or char_length(water_softener_owned) <= 300) and
    (water_softener_age is null or char_length(water_softener_age) <= 300) and
    (sewer_frequency is null or char_length(sewer_frequency) <= 300) and
    (garbage_company is null or char_length(garbage_company) <= 300) and
    (internet_provider is null or char_length(internet_provider) <= 300) and
    (top_features is null or array_length(top_features, 1) <= 40) and
    (top_amenities is null or array_length(top_amenities, 1) <= 40) and
    (what_you_love is null or char_length(what_you_love) <= 4000) and
    (reason_for_selling is null or char_length(reason_for_selling) <= 4000) and
    (additional_comments is null or char_length(additional_comments) <= 4000) and
    (marketing_selections is null or array_length(marketing_selections, 1) <= 40) and
    (showing_instructions is null or char_length(showing_instructions) <= 4000) and
    (buy_before_moving is null or char_length(buy_before_moving) <= 300)
  );

-- Deliberately no select / update / delete policy. Reading happens with the
-- service role key, from Realtor OS, never from the browser bundle.

-- ---------------------------------------------------------------------------
-- public.tenant_intakes -- from tenant_intake_schema.json v1.0.0 (62 fields)
-- PII boundary: gross_monthly_income, employer, additional_income, credit_range
-- must stay out of the Google Sheet mirror; Supabase + local markdown only.
-- ---------------------------------------------------------------------------
create table if not exists public.tenant_intakes (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  full_name                 text,
  email                     text,
  phone                     text,
  current_address           text,
  preferred_contact         text,
  best_contact_time         text[],
  occupant_count            integer,
  coapplicant_name          text,
  coapplicant_email         text,
  coapplicant_phone         text,
  coapplicant_relationship  text,
  target_areas              text,
  commute_to                text,
  max_commute_minutes       integer,
  max_monthly_rent          numeric(12,2),
  rent_includes_utilities   text,
  move_in_date              date,
  date_flexibility          text,
  lease_length              text,
  property_types            text[],
  beds_min                  integer,
  baths_min                 numeric(6,1),
  sqft_min                  integer,
  parking                   text,
  laundry                   text,
  air_conditioning          boolean,
  outdoor_space             text[],
  storage_needed            text,
  furnished                 boolean,
  accessibility_needs       text,
  has_pets                  boolean,
  pet_count                 integer,
  pet_type                  text,
  pet_breed                 text,
  pet_weight                text,
  pet_age                   text,
  pet_reference             text,
  assistance_animal         boolean,
  gross_monthly_income      numeric(12,2),
  employment_status         text,
  employer                  text,
  time_at_employer          text,
  additional_income         text,
  credit_range              text,
  cosigner_available        boolean,
  rental_assistance         boolean,
  current_housing           text,
  current_rent              numeric(12,2),
  time_at_current           text,
  current_landlord_name     text,
  current_landlord_phone    text,
  prior_address             text,
  reason_for_moving         text,
  landlord_contact_ok       boolean,
  deposit_ready             boolean,
  docs_ready                text[],
  tour_availability         text,
  must_haves                text,
  deal_breakers             text,
  other_notes               text,
  agency_ack                boolean,
  contact_consent           boolean
);

comment on table public.tenant_intakes is
  'Write-only intake capture. Generated from tenant_intake_schema.json. No SELECT policy by design.';

alter table public.tenant_intakes enable row level security;
revoke all on public.tenant_intakes from anon, authenticated;
grant insert on public.tenant_intakes to anon;

drop policy if exists "anon may submit tenant_intakes" on public.tenant_intakes;
create policy "anon may submit tenant_intakes"
  on public.tenant_intakes for insert to anon
  with check (
    (full_name is null or char_length(full_name) <= 300) and
    (email is null or char_length(email) <= 300) and
    (phone is null or char_length(phone) <= 300) and
    (current_address is null or char_length(current_address) <= 300) and
    (preferred_contact is null or char_length(preferred_contact) <= 300) and
    (best_contact_time is null or array_length(best_contact_time, 1) <= 40) and
    (coapplicant_name is null or char_length(coapplicant_name) <= 300) and
    (coapplicant_email is null or char_length(coapplicant_email) <= 300) and
    (coapplicant_phone is null or char_length(coapplicant_phone) <= 300) and
    (coapplicant_relationship is null or char_length(coapplicant_relationship) <= 300) and
    (target_areas is null or char_length(target_areas) <= 4000) and
    (commute_to is null or char_length(commute_to) <= 300) and
    (rent_includes_utilities is null or char_length(rent_includes_utilities) <= 300) and
    (date_flexibility is null or char_length(date_flexibility) <= 300) and
    (lease_length is null or char_length(lease_length) <= 300) and
    (property_types is null or array_length(property_types, 1) <= 40) and
    (parking is null or char_length(parking) <= 300) and
    (laundry is null or char_length(laundry) <= 300) and
    (outdoor_space is null or array_length(outdoor_space, 1) <= 40) and
    (storage_needed is null or char_length(storage_needed) <= 300) and
    (accessibility_needs is null or char_length(accessibility_needs) <= 4000) and
    (pet_type is null or char_length(pet_type) <= 300) and
    (pet_breed is null or char_length(pet_breed) <= 300) and
    (pet_weight is null or char_length(pet_weight) <= 300) and
    (pet_age is null or char_length(pet_age) <= 300) and
    (pet_reference is null or char_length(pet_reference) <= 300) and
    (employment_status is null or char_length(employment_status) <= 300) and
    (employer is null or char_length(employer) <= 300) and
    (time_at_employer is null or char_length(time_at_employer) <= 300) and
    (additional_income is null or char_length(additional_income) <= 300) and
    (credit_range is null or char_length(credit_range) <= 300) and
    (current_housing is null or char_length(current_housing) <= 300) and
    (time_at_current is null or char_length(time_at_current) <= 300) and
    (current_landlord_name is null or char_length(current_landlord_name) <= 300) and
    (current_landlord_phone is null or char_length(current_landlord_phone) <= 300) and
    (prior_address is null or char_length(prior_address) <= 4000) and
    (reason_for_moving is null or char_length(reason_for_moving) <= 4000) and
    (docs_ready is null or array_length(docs_ready, 1) <= 40) and
    (tour_availability is null or char_length(tour_availability) <= 4000) and
    (must_haves is null or char_length(must_haves) <= 4000) and
    (deal_breakers is null or char_length(deal_breakers) <= 4000) and
    (other_notes is null or char_length(other_notes) <= 4000)
  );

-- Deliberately no select / update / delete policy. Reading happens with the
-- service role key, from Realtor OS, never from the browser bundle.

commit;

-- POST-APPLY VERIFICATION (run with the ANON key, not the service role):
--   anon INSERT  -> 201
--   anon SELECT  -> []      <- must be empty even though the row exists
--   anon DELETE  -> 0 rows
-- An empty [] on its own proves nothing when a table is empty. Insert a canary
-- first, then try to read that exact row back.
