/**
 * Municipality hero images.
 *
 * Auto-generated by generate_municipality_images.py using Fal.AI Flux Pro.
 * To regenerate: python generate_municipality_images.py
 */

export interface MunicipalityImage {
  src: string;
  alt: string;
}

const municipalityImages: Record<string, MunicipalityImage> = {
  bay_view: {
    src: "/municipality-images/bay_view.jpg",
    alt: "Worker cottages home in Bay View (within Milwaukee), Wisconsin — CreativeClass and FoodieParadise",
  },
  bayside: {
    src: "/municipality-images/bayside.jpg",
    alt: "Mid-century ranch home in Bayside, Wisconsin — NorthShoreExclusive and TopRatedSchools",
  },
  belgium: {
    src: "/municipality-images/belgium.jpg",
    alt: "Ranch home in Belgium, Wisconsin — RuralRetreat and SmallTownPeace",
  },
  big_bend: {
    src: "/municipality-images/big_bend.jpg",
    alt: "Ranch-style homes (most common) home in Big Bend, Wisconsin — RiverVillage and SmallTownAuthentic",
  },
  brookfield: {
    src: "/municipality-images/brookfield.jpg",
    alt: "Executive colonials, newer construction, luxury condos, estate properties home in Brookfield (City), Wisconsin — TopSchools and UpscaleSuburb",
  },
  brown_deer: {
    src: "/municipality-images/brown_deer.jpg",
    alt: "Mid-century ranches home in Brown Deer, Wisconsin — DiverseCommunity and AffordableNorthSide",
  },
  butler: {
    src: "/municipality-images/butler.jpg",
    alt: "Mid-century ranch home in Butler, Wisconsin — AffordableSuburb and BlueCollarCharm",
  },
  cedarburg: {
    src: "/municipality-images/cedarburg.jpg",
    alt: "Historic Cream City brick home in Cedarburg, Wisconsin — HistoricCharm and WalkableDowntown",
  },
  chenequa: {
    src: "/municipality-images/chenequa.jpg",
    alt: "Lakefront estates home in Chenequa, Wisconsin — LakefrontEstate and UltraLuxury",
  },
  cudahy: {
    src: "/municipality-images/cudahy.jpg",
    alt: "Pre-war bungalows home in Cudahy, Wisconsin — LakefrontValue and FirstTimeBuyer",
  },
  delafield: {
    src: "/municipality-images/delafield.jpg",
    alt: "Historic estates, lakefront luxury, newer executive homes, upscale condos home in Delafield, Wisconsin — NatureLovers and KettleMoraine",
  },
  dousman: {
    src: "/municipality-images/dousman.jpg",
    alt: "Updated family homes home in Dousman, Wisconsin — TrailTown and BlueRibbonSchools",
  },
  eagle: {
    src: "/municipality-images/eagle.jpg",
    alt: "Contemporary builds home in Eagle, Wisconsin — KettleMoraineLife and OutdoorAdventurer",
  },
  elm_grove: {
    src: "/municipality-images/elm_grove.jpg",
    alt: "Classic colonials home in Elm Grove, Wisconsin — VillagePrestige and TopSchools",
  },
  fox_point: {
    src: "/municipality-images/fox_point.jpg",
    alt: "1940s-1960s Colonials home in Fox Point, Wisconsin — NorthShoreElegance and LakefrontBluffs",
  },
  franklin: {
    src: "/municipality-images/franklin.jpg",
    alt: "Newer construction subdivisions (2000s-present) home in Franklin, Wisconsin — NewConstruction and SportsLifestyle",
  },
  fredonia: {
    src: "/municipality-images/fredonia.jpg",
    alt: "Historic 19th-century settler homes home in Fredonia, Wisconsin — SmallTownLiving and RuralCharm",
  },
  germantown: {
    src: "/municipality-images/germantown.jpg",
    alt: "Colonial home in Germantown, Wisconsin — Suburban and FamilyFriendly",
  },
  glendale: {
    src: "/municipality-images/glendale.jpg",
    alt: "Mid-century ranches home in Glendale, Wisconsin — NorthShoreValue and BayshoreLiving",
  },
  grafton: {
    src: "/municipality-images/grafton.jpg",
    alt: "Mid-century ranch home in Grafton, Wisconsin — BestValue and FamilyFirst",
  },
  greendale: {
    src: "/municipality-images/greendale.jpg",
    alt: "Original 1930s Greenbelt-era Colonials home in Greendale, Wisconsin — HistoricVillage and WalkableDowntown",
  },
  greenfield: {
    src: "/municipality-images/greenfield.jpg",
    alt: "Post-war ranches home in Greenfield, Wisconsin — QuietSuburb and AffordableFamily",
  },
  hales_corners: {
    src: "/municipality-images/hales_corners.jpg",
    alt: "1950s ranch (most prevalent) home in Hales Corners, Wisconsin — NatureRich and BotanicalBeauty",
  },
  hartford: {
    src: "/municipality-images/hartford.jpg",
    alt: "Classic Wisconsin ranches and bungalows in established neighborhoods home in Hartford, Wisconsin — ParksAndRec and SmallTownVibe",
  },
  hartland: {
    src: "/municipality-images/hartland.jpg",
    alt: "Traditional colonials home in Hartland, Wisconsin — VillageLife and ArrowheadSchools",
  },
  jackson: {
    src: "/municipality-images/jackson.jpg",
    alt: "Newer suburban construction (2000s-2020s) home in Jackson, Wisconsin — NewerHomes and FamilyFriendly",
  },
  kewaskum: {
    src: "/municipality-images/kewaskum.jpg",
    alt: "Traditional ranch and two-story homes on generous lots home in Kewaskum, Wisconsin — CountryLiving and Rural",
  },
  lac_la_belle: {
    src: "/municipality-images/lac_la_belle.jpg",
    alt: "Historic Victorian mansions from the 1870s lakefront resort era home in Lac La Belle, Wisconsin — LakefrontLiving and HiddenGem",
  },
  lannon: {
    src: "/municipality-images/lannon.jpg",
    alt: "Mid-century ranches home in Lannon, Wisconsin — QuarryCountry and FastestGrowing",
  },
  menomonee_falls: {
    src: "/municipality-images/menomonee_falls.jpg",
    alt: "Mid-century ranches home in Menomonee Falls, Wisconsin — SmallTownCharm and TrailLife",
  },
  mequon: {
    src: "/municipality-images/mequon.jpg",
    alt: "Colonial, contemporary ranch, estate-style on large lots home in Mequon, Wisconsin — UpscaleSuburban and TopSchools",
  },
  merton: {
    src: "/municipality-images/merton.jpg",
    alt: "Colonial Revival home in Merton, Wisconsin — LakeCountryHeart and TopSchools",
  },
  milwaukee: {
    src: "/municipality-images/milwaukee.jpg",
    alt: "Milwaukee bungalows home in Milwaukee (City Proper), Wisconsin — UrbanLiving and AffordableCity",
  },
  mukwonago: {
    src: "/municipality-images/mukwonago.jpg",
    alt: "Single-family ranch homes home in Mukwonago, Wisconsin — SmallTownLiving and AffordableEntry",
  },
  muskego: {
    src: "/municipality-images/muskego.jpg",
    alt: "Larger-lot single-family homes home in Muskego, Wisconsin — TopSchools and LakeAccess",
  },
  nashotah: {
    src: "/municipality-images/nashotah.jpg",
    alt: "Traditional colonials home in Nashotah, Wisconsin — LakeCountryHeritage and TopSchools",
  },
  new_berlin: {
    src: "/municipality-images/new_berlin.jpg",
    alt: "Ranch homes home in New Berlin, Wisconsin — SpaceToGrow and FamilyFirst",
  },
  newburg: {
    src: "/municipality-images/newburg.jpg",
    alt: "Older homes with historic character from 1840s settlement era home in Newburg, Wisconsin — RiversideVillage and NatureLovers",
  },
  north_prairie: {
    src: "/municipality-images/north_prairie.jpg",
    alt: "Midcentury ranch-style home in North Prairie, Wisconsin — FamilyFirst and UpscaleRural",
  },
  oak_creek: {
    src: "/municipality-images/oak_creek.jpg",
    alt: "Mix of 1960s-1980s ranches and split-levels home in Oak Creek, Wisconsin — TownSquareLiving and DiverseCommunity",
  },
  oconomowoc: {
    src: "/municipality-images/oconomowoc.jpg",
    alt: "Historic lakefront estates home in Oconomowoc, Wisconsin — LakefrontCharm and WalkableDowntown",
  },
  pewaukee: {
    src: "/municipality-images/pewaukee.jpg",
    alt: "Lakefront properties home in Pewaukee (City/Village), Wisconsin — LakeLife and WaterfrontDining",
  },
  port_washington: {
    src: "/municipality-images/port_washington.jpg",
    alt: "Victorian and Craftsman in the historic district home in Port Washington, Wisconsin — LakefrontLiving and HarborTown",
  },
  richfield: {
    src: "/municipality-images/richfield.jpg",
    alt: "Executive-level colonials home in Richfield, Wisconsin — Luxury and Private",
  },
  river_hills: {
    src: "/municipality-images/river_hills.jpg",
    alt: "Estate homes on 1-5+ acre lots home in River Hills, Wisconsin — EstateLiving and UltraExclusive",
  },
  saukville: {
    src: "/municipality-images/saukville.jpg",
    alt: "Ranch home in Saukville, Wisconsin — BudgetFriendly and OutdoorAdventurer",
  },
  shorewood: {
    src: "/municipality-images/shorewood.jpg",
    alt: "1920s Colonials home in Shorewood, Wisconsin — WalkableVillage and CulturalHub",
  },
  slinger: {
    src: "/municipality-images/slinger.jpg",
    alt: "Mix of newer subdivision homes (2000s-2020s) home in Slinger, Wisconsin — TopSchools and SmallTownVibe",
  },
  south_milwaukee: {
    src: "/municipality-images/south_milwaukee.jpg",
    alt: "Worker cottages home in South Milwaukee, Wisconsin — HiddenGem and LakefrontTrails",
  },
  st_francis: {
    src: "/municipality-images/st_francis.jpg",
    alt: "Small post-war bungalows home in St. Francis, Wisconsin — SleeperPick and LakefrontBudget",
  },
  sussex: {
    src: "/municipality-images/sussex.jpg",
    alt: "Newer construction single-family homes home in Sussex, Wisconsin — NewerConstruction and GrowingCommunity",
  },
  thiensville: {
    src: "/municipality-images/thiensville.jpg",
    alt: "Cape Cod home in Thiensville, Wisconsin — VillageCharm and FoodieDestination",
  },
  wales: {
    src: "/municipality-images/wales.jpg",
    alt: "Colonial Revival home in Wales, Wisconsin — KettleMoraineGateway and TrailConvergence",
  },
  waukesha: {
    src: "/municipality-images/waukesha.jpg",
    alt: "Cape Cods home in City of Waukesha, Wisconsin — DowntownVibes and FirstTimeBuyer",
  },
  wauwatosa: {
    src: "/municipality-images/wauwatosa.jpg",
    alt: "1920s-1940s Colonials and Tudors home in Wauwatosa, Wisconsin — FamilyFriendly and TopSchools",
  },
  west_allis: {
    src: "/municipality-images/west_allis.jpg",
    alt: "Post-war Cape Cods home in West Allis, Wisconsin — AffordableSuburb and BlueCollarCharm",
  },
  west_bend: {
    src: "/municipality-images/west_bend.jpg",
    alt: "Mix of historic craftsman and bungalow homes downtown home in West Bend, Wisconsin — FirstTimeBuyer and ArtsAndCulture",
  },
  west_milwaukee: {
    src: "/municipality-images/west_milwaukee.jpg",
    alt: "Milwaukee-style bungalows home in West Milwaukee, Wisconsin — AffordableEntry and UrbanSuburbanMix",
  },
  whitefish_bay: {
    src: "/municipality-images/whitefish_bay.jpg",
    alt: "Tudor Revivals home in Whitefish Bay, Wisconsin — NorthShoreElite and TopSchools",
  },
};

export default municipalityImages;
